# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache:
  bundler: true

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

script: COVERAGE=true bundle exec rspec

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
