language: ruby
cache:
  bundler: true

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

script: COVERAGE=true bundle exec rspec

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
