branches:
  only:
    - master
script: "COVERAGE=true ruby -Ilib:test test/all.rb"
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rbx
matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: rbx
      gemfile: gemfiles/Gemfile.rbx
